version: '3.8'

services:
  ffmpeg-dev:
    container_name: ffmpeg-dev-3
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.vscode-for-docker:/app/.vscode
      #- ./src:/app/src
    working_dir: /app
    tty: true
volumes:
  src:
