version: '3.8'

services:
  ffmpeg-dev:
    container_name: ffmpeg-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.vscode-for-docker:/app/.vscode
    working_dir: /app
    tty: true
volumes:
  src:
